[tool.poetry]
name = "fsm-coding assignments"
version = "0.1.0"
description = ""
authors = ["zem9401 <1261864544@qq.com>"]

[tool.poetry.dependencies]
python = "^3.8.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
